### PR TITLE
offboard bpitts, elim [SE-2618]

### PR DESCRIPTION
**Pull request by floatingatoll**
I'm not sure who runs this script or needs to deploy updates to it, and it might well be maintained elsewhere than GitHub these days. We'll see.

### CODE REVIEW

**Review by gcoxmoz — APPROVED** [review]
I don't really know what these do, but I sure can't disagree with the removals.

**Comment by gene1wood** [comment]
This code alone does not revoke the rights of Google Workspace super admins. You'll also need to have a superadmin go in and remove the non-SSO-controlled user

**Comment by gene1wood** [comment]
> You'll also need to have a superadmin go in and remove the non-SSO-controlled user

As I still have these rights, I've removed superadmin rights from bpitts-owner@gcp.infra.mozilla.com

**Comment by floatingatoll** [comment]
As superadmin, I had previously blocked/suspended the accounts listed, but this PR does still need to ship.

**Comment by floatingatoll** [comment]
Okay, I was able to get it building and deploying, and to run successfully. It crashed halfway through due to some sort of inconsistency (since it apparently hasn't been working correctly for at least a month). But for offboard purposes, done.

**Pull request merged**
